name: window_states
description: Effortless Window State Transitions for Flutter Desktop
version: 0.1.2
repository: https://github.com/deepraj02/window_states


environment:
  sdk: ^3.8.1
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  screen_retriever: ^0.2.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
